[feat] S1-R41 신재생에너지 비율 데이터 전송 구현
web-eco-location/eco-location-back pull request #28
Opened 2023-05-12 07:55 UTC by NoMaL21

구현 내용은 #23 에 작성되어 있습니다.

close #23

2023-05-15 02:27 UTC, Jeonwoojae commented on eco-location-back/src/main/java/kr/ac/kumoh/webkit/ecolocationback/dto/AreaGeneratorSourceDto.java
>      private String time;
뜻에 맞게 Date타입이면 추후 사용하기 편할 것 같습니다

2023-05-15 02:27 UTC, Jeonwoojae approved these changes
확인했습니다

2023-05-15 05:16 UTC, NoMaL21 commented
데이터포멧으로 Date로 변환하려다 잘 안되서 그냥 csv파일을 입력할 때 바꾸는 식으로 바꾸겠습니다

2023-05-15 07:53 UTC, NoMaL21 commented
csv파일을 바꿔두었고, csvwirter도 바꿔두었습니다.

2023-05-15 08:02 UTC, Jeonwoojae commented on eco-location-back/src/main/java/kr/ac/kumoh/webkit/ecolocationback/controller/AreaGeneratorSourceController.java
> +    public List<AreaGeneratorSource> getAreaGeneratorSourcesBetweenTime(@RequestParam("StartTime") String StartTime, @RequestParam("EndTime") String EndTime) {
Time -> Date가 더 알맞는 것 같습니다

2023-05-15 08:04 UTC, Jeonwoojae requested changes
수정할 부분 더 수정해 주시면 다시 확인하겠습니다

2023-05-17 02:17 UTC, Jeonwoojae commented on eco-location-back/src/main/java/kr/ac/kumoh/webkit/ecolocationback/controller/AreaGeneratorSourceController.java
> +@RequestMapping("/areageneratorsource")
주소가 길게 나타나고 무슨 의미인지 알아보기 어려울 것 같습니다.

2023-05-17 02:21 UTC, Jeonwoojae approved these changes
확인했습니다

2023-05-17 04:32 UTC, NoMaL21 commented on eco-location-back/src/main/java/kr/ac/kumoh/webkit/ecolocationback/controller/AreaGeneratorSourceController.java
> +@RequestMapping("/areageneratorsource")
추후에 알맞은 주소로 협의를 거쳐 수정하면 될 것 같습니다.

2023-05-17 04:33 UTC, merged